export const languageModels = [
  // 'anthropic/claude-3-haiku',
  // 'anthropic/claude-3-opus',
  // 'anthropic/claude-3.5-haiku',
  // 'anthropic/claude-3.5-sonnet',
  // 'anthropic/claude-3.5-sonnet-20240620',
  // 'anthropic/claude-3.7-sonnet',
  // 'anthropic/claude-haiku-4.5',
  // 'anthropic/claude-opus-4',
  // 'anthropic/claude-opus-4.1',
  // 'anthropic/claude-sonnet-4',
  // 'anthropic/claude-sonnet-4.5',
  // 'google/gemini-2.0-flash',
  // 'google/gemini-2.0-flash-lite',
  // 'google/gemini-2.5-flash',
  // 'google/gemini-2.5-flash-image',
  // 'google/gemini-2.5-flash-image-preview',
  // 'google/gemini-2.5-flash-lite',
  // 'google/gemini-2.5-flash-lite-preview-09-2025',
  // 'google/gemini-2.5-flash-preview-09-2025',
  // 'google/gemini-2.5-pro',
  // 'google/gemini-3-pro-preview',
  // 'google/gemini-3-pro-image',
  // 'openai/gpt-3.5-turbo',
  // 'openai/gpt-3.5-turbo-instruct',
  // 'openai/gpt-4-turbo',
  'openai/gpt-4.1',
  // 'openai/gpt-4.1-mini',
  // 'openai/gpt-4.1-nano',
  // 'openai/gpt-4o',
  // 'openai/gpt-4o-mini',
  'openai/gpt-5',
  // 'openai/gpt-5-chat',
  // 'openai/gpt-5-codex',
  // 'openai/gpt-5-mini',
  // 'openai/gpt-5-nano',
  // 'openai/gpt-5-pro',
  // 'openai/gpt-5.1-codex',
  // 'openai/gpt-5.1-codex-mini',
  // 'openai/gpt-5.1-instant',
  // 'openai/gpt-5.1-thinking',
  // 'openai/gpt-oss-120b',
  // 'openai/gpt-oss-20b',
  // 'openai/gpt-oss-safeguard-20b',
  // 'openai/o1',
  // 'openai/o3',
  // 'openai/o3-deep-research',
  // 'openai/o3-mini',
  // 'openai/o4-mini',
  // 'xai/grok-2',
  // 'xai/grok-2-vision',
  // 'xai/grok-3',
  // 'xai/grok-3-fast',
  // 'xai/grok-3-mini',
  // 'xai/grok-3-mini-fast',
  // 'xai/grok-4',
  // 'xai/grok-4-fast-non-reasoning',
  // 'xai/grok-4-fast-reasoning',
  // 'xai/grok-code-fast-1',
]

export const embeddingModels = [
  // 'google/gemini-embedding-001',
  // 'google/text-embedding-005',
  // 'google/text-multilingual-embedding-002',
  // 'openai/text-embedding-3-large',
  'openai/text-embedding-3-small',
  // 'openai/text-embedding-ada-002',
]
